name: 'Husarnet'
description: 'Accessing other devices from Husarnet VPN network in GitHub workflow'
inputs:
  joincode:
    description: 'A JoinCode for the Husarnet network you want to connect to'
    required: true
  hostname: 
    description: 'A hostname under which this workflow will be available in your Husarnet network'
    default: 'my-github-action'
  cache-key: 
    description: 'Thanks to cache, IPv6 address will be the same in the following job runs. Another cache means generating another peer.'
    default: 'husarnet-volume'
  cache-enabled: 
    description: 'Cache is enabled by default, but you can disable it by using this flag'
    default: true
outputs:
  ipv6:
    description: "Husarnet IPv6 address of this hosts"
    value: ${{ steps.random-number-generator.outputs.random-id }}
  # peers:
  #   description: "Known other Husarnet hosts for this workflow"
  #   value: ...
runs:
  using: "composite"
  steps:
  - name: Cache Husarnet
    id: cache-husarnet-v
    uses: actions/cache@v2
    with:
      path: ${{ github.workspace }}/husarnet_cache
      key: ${{ inputs.cache-key }}

  - name: Installing Husarnet
    run: curl https://install.husarnet.com/install.sh | sudo bash

  - name: Restoring /var/lib/husarnet from cache
    if: steps.cache-husarnet-v.outputs.cache-hit == 'true'
    run: |  
      sudo \cp -af ${{ github.workspace }}/husarnet_cache/. /var/lib/husarnet
      sudo chown -R root:root /var/lib/husarnet

  - name: Waiting for Husarnet to be ready
    run: |  
      sudo systemctl restart husarnet

      while [ $(sudo husarnet status | grep "ERROR" | wc -l) -gt 0 ]; do echo .; sleep 1; done

      sudo husarnet status

  - name: Joining to Husarnet network
    # if: steps.cache-husarnet-v.outputs.cache-hit != 'true'
    run: sudo husarnet join ${{ inputs.joincode }} ${{ inputs.hostname }}

  - name: Saving /var/lib/husarnet to cache
    run: |
      mkdir -p ${{ github.workspace }}/husarnet_cache
      sudo \cp -af /var/lib/husarnet/. ${{ github.workspace }}/husarnet_cache
      sudo chmod -R a+rwx ${{ github.workspace }}/husarnet_cache

  # - name: Husarnet VPN
  #   uses: ./.github/actions/husarnet
  #     with:
  #       joincode: abcde
  #       hostname: my-hostname
  #       cache-id: husarnet-v
  #       cache-enabled: true