name: Upload ISO file

on:
  push:
    branches:
      - 'main'
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install platformio & build
      run: |
        pip3 install -U platformio
        pio run 
        ls -la
        ls .pio/build/esp32dev
        
