name: Upload ISO file

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Husarnet
      id: cache-husarnet-v
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/husarnet_cache
        key: husarnet-vol

    - name: Installing Husarnet
      run: curl https://install.husarnet.com/install.sh | sudo bash

    - name: Restoring /var/lib/husarnet from cache
      if: steps.cache-husarnet-v.outputs.cache-hit == 'true'
      run: |  
        sudo \cp -af ${{ github.workspace }}/husarnet_cache/. /var/lib/husarnet
        sudo chown -R root:root /var/lib/husarnet

    - name: Waiting for Husarnet to be ready
      run: |  
        sudo systemctl restart husarnet
        sleep 1
        sudo husarnet status
        sleep 5
        sudo husarnet status

    - name: Joining to Husarnet network
      # if: steps.cache-husarnet-v.outputs.cache-hit != 'true'
      run: |
        sudo husarnet join ${{ secrets.HUSARNET_JOINCODE }} github
        sudo husarnet status

    - name: Saving /var/lib/husarnet to cache
      run: |
        mkdir -p ${{ github.workspace }}/husarnet_cache
        sudo \cp -af /var/lib/husarnet/. ${{ github.workspace }}/husarnet_cache
        sudo chmod -R a+rwx ${{ github.workspace }}/husarnet_cache
        
    - name: Installing platformio & build
      run: |
        export ENV_WIFI_SSID=${{ secrets.WIFI_SSID }}
        export ENV_WIFI_PASS=${{ secrets.WIFI_PASS }}
        export ENV_HUSARNET_JOINCODE=${{ secrets.HUSARNET_JOINCODE }}
        pip3 install -U platformio
        pio run
        ls -la
        ls .pio/build/esp32dev
    
    - name: Uploading a firmware to ESP32
      run: >
        curl -# -v
        -H 'Accept: */*'
        -H 'Accept-Encoding: gzip, deflate'
        -H 'Connection: keep-alive'
        -F "MD5="$(md5sum "${{ github.workspace }}/.pio/build/esp32dev/firmware.bin" | cut -d ' ' -f 1)""
        -F 'firmware=@${{ github.workspace }}/.pio/build/esp32dev/firmware.bin'
        'http://ota-test:3232/update'
