name: Upload ISO file

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Connecting to Husarnet VPN network
      uses: husarnet/husarnet-action@v1
      id: husarnet
      with:
        join-code: ${{ secrets.HUSARNET_JOINCODE }}

    - name: ESP32 software reset
      run: curl -X POST 'http://ota-test:3232/reset'

    - name: Installing platformio & build
      run: |
        export ENV_WIFI_SSID=${{ secrets.WIFI_SSID }}
        export ENV_WIFI_PASS=${{ secrets.WIFI_PASS }}
        export ENV_HUSARNET_JOINCODE=${{ secrets.HUSARNET_JOINCODE }}
        pip3 install -U platformio
        pio run
        ls -la .pio/build/esp32dev

    - name: Uploading a firmware to ESP32
      run: >
        curl --http0.9 -# -v
        -H 'Accept: */*'
        -H 'Accept-Encoding: gzip, deflate'
        -H 'Connection: keep-alive'
        -F "MD5="$(md5sum "${{ github.workspace }}/.pio/build/esp32dev/firmware.bin" | cut -d ' ' -f 1)""
        -F 'firmware=@${{ github.workspace }}/.pio/build/esp32dev/firmware.bin'
        'http://ota-test:3232/update'

    - name: Stop husarnet
      run: sudo systemctl stop husarnet
