name: Upload ISO file

on:
  push:
    branches:
      - 'main'
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Installing platformio & build
      run: |
        export ENV_WIFI_SSID=${{ secrets.WIFI_SSID }}
        export ENV_WIFI_PASS=${{ secrets.WIFI_PASS }}
        export ENV_HUSARNET_JOINCODE=${{ secrets.HUSARNET_JOINCODE }}
        pip3 install -U platformio
        pio run
        ls -la
        ls .pio/build/esp32dev
        
    - name: Installing & Connecting Husarnet
      run: |
        curl https://install.husarnet.com/install.sh | sudo bash
        sudo systemctl restart husarnet
        sudo husarnet join ${{ secrets.HUSARNET_JOINCODE }} github

    - name: Uploading a firmware to ESP32
      run: >
        curl -# -v POST
        'http://ota-test:3232/update'
        -H 'Accept: */*'
        -H 'Accept-Encoding: gzip, deflate'
        -H 'Connection: keep-alive'
        --form "MD5="$(md5sum "${{ github.workspace }}/.pio/build/esp32dev/firmware.bin" | cut -d ' ' -f 1)""
        --form 'firmware=@${{ github.workspace }}/.pio/build/esp32dev/firmware.bin'
