name: Upload ISO file

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

      # sudo mkdir -p /var/lib/husarnet && sudo touch $_/id
    - name: Installing & Connecting Husarnet
      run: |
        curl https://install.husarnet.com/install.sh | sudo bash
        sudo systemctl restart husarnet
        sleep 2
        echo addr after installation:
        sudo husarnet status
        sleep 5
        sudo bash -c "echo fc94:9093:8538:dac4:be5d:6614:90ec:fba6 c20a52eda19f5d9f27c6435cfb070c7657bb493731e08626d61d36b7a2fdc4d4 e70a72535e95d48f7929d3db201c1846ad49045a0c1770398cc7c6adcf7a22f1c20a52eda19f5d9f27c6435cfb070c7657bb493731e08626d61d36b7a2fdc4d4 > /var/lib/husarnet/id"
        sleep 5
        sudo systemctl restart husarnet
        sleep 5
        sudo husarnet status
        sudo systemctl restart husarnet
        sleep 10
        sudo husarnet status
        sudo husarnet join ${{ secrets.HUSARNET_JOINCODE }} github

    - name: Installing platformio & build
      run: |
        export ENV_WIFI_SSID=${{ secrets.WIFI_SSID }}
        export ENV_WIFI_PASS=${{ secrets.WIFI_PASS }}
        export ENV_HUSARNET_JOINCODE=${{ secrets.HUSARNET_JOINCODE }}
        pip3 install -U platformio
        pio run
        ls -la
        ls .pio/build/esp32dev

    - name: Pinging ESP32
      run: ping6 -c 10 ota-test

    - name: Husarnet status
      run: sudo husarnet status
        
    - name: Uploading a firmware to ESP32
      run: >
        curl -# -v
        -H 'Accept: */*'
        -H 'Accept-Encoding: gzip, deflate'
        -H 'Connection: keep-alive'
        -F "MD5="$(md5sum "${{ github.workspace }}/.pio/build/esp32dev/firmware.bin" | cut -d ' ' -f 1)""
        -F 'firmware=@${{ github.workspace }}/.pio/build/esp32dev/firmware.bin'
        'http://ota-test:3232/update'

    - name: Testing how much time it takes to go online after reboot
      run: ping6 -c 50 ota-test